import { CONTENT } from '../content.js';
import * as F from '../core/finance.js';
import { linspace, mean } from '../core/special.js';
import { lineChart, histogram, heatmap, binomialTreeChart } from '../core/charts.js';
import { theoryCard, field, rangeField, selectField, tabs, table, metric, interpretation, errorBox, qs, bindRange, getn, getv, num, money, pct, downloadCsv, toast, escapeHtml } from '../core/ui.js';
import { runWorker } from '../core/worker-client.js';

const activeTab={};
const state={};
function st(id,defaults){return state[id]??=(structuredClone(defaults));}
function tabbed(moduleId,root,items,renderTab){const a=activeTab[moduleId]||items[0][0];activeTab[moduleId]=a;root.innerHTML=tabs(items,a)+`<div id="sub-root"></div>`;root.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{activeTab[moduleId]=b.dataset.tab;renderModule(moduleId,root)}));renderTab(a,root.querySelector('#sub-root'));}
function controlGrid(inner){return `<div class="control-grid">${inner}</div>`}
function outputGrid(inner){return `<div class="metric-grid">${inner}</div>`}
function chartBox(id,title=''){return `<section class="chart-card">${title?`<div class="chart-title">${escapeHtml(title)}</div>`:''}<div id="${id}" class="chart"></div></section>`}
function section(sub,controls,outputs,extra=''){return `${theoryCard(sub)}<div class="lab-layout"><section class="panel"><div class="panel-title">Inputs</div>${controls}</section><section class="workspace">${outputs}${extra}</section></div>`}
function bindNums(root,ids,fn){ids.forEach(id=>root.querySelector(`#${id}`)?.addEventListener('input',fn));}
function loading(btn,on,label='Running…'){if(!btn)return;btn.disabled=on;btn.dataset.old??=btn.textContent;btn.textContent=on?label:btn.dataset.old;}

// 1. Forward
function renderForward(root){const m=CONTENT.modules.forward,s=st('forward',{F:1020,qS:0,qF:1,inspect:1050,S0:100,r:.05,delta:.02,T:1,market:105});tabbed('forward',root,[['payoff','Payoff builder'],['pricing','Fair price & arbitrage']],(t,r)=>{
  if(t==='payoff'){
    const sub=m.submodules.payoff;r.innerHTML=section(sub,controlGrid(field('Forward price F₀,T','fw-F',s.F,{step:1})+field('Underlying quantity q_S','fw-qS',s.qS,{step:.25})+field('Forward quantity q_F','fw-qF',s.qF,{step:.25})+field('Inspector S_T','fw-inspect',s.inspect,{step:1})),`<div id="fw-metrics" class="metric-grid"></div>${chartBox('fw-chart','Expiration payoff / terminal value')}`,'' );
    const update=()=>{s.F=getn('fw-F');s.qS=getn('fw-qS');s.qF=getn('fw-qF');s.inspect=getn('fw-inspect');const lo=Math.max(0,s.F*.65),hi=s.F*1.35,x=linspace(lo,hi,121),yl=x.map(ST=>F.longForwardPayoff(ST,s.F)),ys=x.map(ST=>F.shortForwardPayoff(ST,s.F)),yc=x.map(ST=>F.combinedTerminalPayoff(ST,s.F,s.qS,s.qF));qs('#fw-metrics',r).innerHTML=metric('Long forward at inspector',money(F.longForwardPayoff(s.inspect,s.F)))+metric('Short forward at inspector',money(F.shortForwardPayoff(s.inspect,s.F)))+metric('Combined terminal value',money(F.combinedTerminalPayoff(s.inspect,s.F,s.qS,s.qF)));lineChart(qs('#fw-chart',r),[{name:'Long forward',x,y:yl},{name:'Short forward',x,y:ys},{name:'Combined position',x,y:yc}],{xLabel:'S_T',yLabel:'Payoff / terminal value'});};bindNums(r,['fw-F','fw-qS','fw-qF','fw-inspect'],update);update();
  } else {
    const sub=m.submodules.pricing;r.innerHTML=section(sub,controlGrid(field('Spot S₀','fw-S0',s.S0)+field('Risk-free rate r','fw-r',s.r,{step:.005})+field('Dividend yield δ','fw-d',s.delta,{step:.005})+field('Maturity T','fw-T',s.T,{step:.25})+field('Observed market forward','fw-market',s.market,{step:.5})),`<div id="fw-price-metrics" class="metric-grid"></div><div id="fw-arb" class="interpretation"></div>`);
    const update=()=>{s.S0=getn('fw-S0');s.r=getn('fw-r');s.delta=getn('fw-d');s.T=getn('fw-T');s.market=getn('fw-market');try{const fair=F.fairForwardPrice(s.S0,s.r,s.delta,s.T),arb=F.diagnoseForwardArbitrage(s.S0,s.market,s.r,s.delta,s.T);qs('#fw-price-metrics',r).innerHTML=metric('Fair F₀,T',money(fair,4))+metric('Market − fair',money(s.market-fair,4))+metric('Maturity arbitrage profit/unit',money(arb.maturityProfitPerUnit,4));qs('#fw-arb',r).innerHTML=`<strong>${arb.relation==='fair'?'No arbitrage detected':arb.relation==='market_above_fair'?'Cash-and-carry':'Reverse cash-and-carry'}.</strong><ol>${arb.strategy.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ol>`;}catch(e){qs('#fw-arb',r).outerHTML=errorBox(e.message)}};bindNums(r,['fw-S0','fw-r','fw-d','fw-T','fw-market'],update);update();
  }
});}

// 2. Futures
function renderFutures(root){const m=CONTENT.modules.futures,s=st('futures',{prices:F.LECTURE_SP500_FUTURES_PRICES.join(', '),mult:250,n:8,margin:.10,r:.06,ppy:52,maint:.70,pos:'long',rho:.9284,sS:.0263,sF:.0313,QA:2000000,QF:42000,exp:'will_purchase'});tabbed('futures',root,[['margin','Margin account'],['cross_hedge','Cross hedging']],(t,r)=>{
  if(t==='margin'){const sub=m.submodules.margin;r.innerHTML=`${theoryCard(sub)}<div class="lab-layout"><section class="panel"><div class="panel-title">Inputs</div><label class="field"><span>Settlement prices (comma-separated)</span><textarea id="fu-prices" rows="5">${escapeHtml(s.prices)}</textarea></label>${controlGrid(field('Contract multiplier','fu-mult',s.mult)+field('Number of contracts','fu-n',s.n,{step:1})+field('Initial margin rate','fu-margin',s.margin,{step:.01})+field('Risk-free rate r','fu-r',s.r,{step:.005})+field('Periods/year','fu-ppy',s.ppy,{step:1})+field('Maintenance / initial margin','fu-maint',s.maint,{step:.05})+selectField('Position','fu-pos',['long','short'],s.pos))}</section><section class="workspace"><div id="fu-metrics" class="metric-grid"></div>${chartBox('fu-chart','Margin account balance')}<div id="fu-table"></div><button id="fu-csv" class="secondary">Download path CSV</button></section></div>`;
    let latest=null;const update=()=>{try{s.prices=qs('#fu-prices',r).value;s.mult=getn('fu-mult');s.n=getn('fu-n');s.margin=getn('fu-margin');s.r=getn('fu-r');s.ppy=getn('fu-ppy');s.maint=getn('fu-maint');s.pos=getv('fu-pos');const p=s.prices.split(/[ ,;\n]+/).filter(Boolean).map(Number);latest=F.marginAccountPath(p,s.mult,s.n,s.margin,s.r,s.ppy,s.maint,s.pos);qs('#fu-metrics',r).innerHTML=metric('Initial notional',money(latest.initialNotional))+metric('Initial margin',money(latest.initialMargin))+metric('Maintenance margin',money(latest.maintenanceMargin))+metric('Futures profit',money(latest.futuresProfit))+metric('Comparable forward profit',money(latest.forwardProfit))+metric('Margin calls',latest.marginCall.filter(Boolean).length);lineChart(qs('#fu-chart',r),[{name:'Margin balance',x:latest.periods,y:latest.marginBalance},{name:'Maintenance margin',x:latest.periods,y:latest.periods.map(()=>latest.maintenanceMargin)}],{xLabel:'Settlement period',yLabel:'Margin balance'});const rows=latest.periods.map((tt,i)=>[tt,money(latest.futuresPrices[i],2),i?money(latest.priceChanges[i],2):'—',money(latest.interestEarned[i],2),money(latest.markToMarket[i],2),money(latest.marginBalance[i],2),latest.marginCall[i]?'CALL':'']);qs('#fu-table',r).innerHTML=table(['Period','F','ΔF','Interest','MTM','Balance','Margin call'],rows);}catch(e){qs('#fu-metrics',r).innerHTML=errorBox(e.message)}};['fu-prices','fu-mult','fu-n','fu-margin','fu-r','fu-ppy','fu-maint','fu-pos'].forEach(id=>r.querySelector(`#${id}`)?.addEventListener('input',update));qs('#fu-csv',r).onclick=()=>latest&&downloadCsv('futures_margin.csv',['period','price','change','interest','mtm','balance','margin_call'],latest.periods.map((tt,i)=>[tt,latest.futuresPrices[i],latest.priceChanges[i]??'',latest.interestEarned[i],latest.markToMarket[i],latest.marginBalance[i],latest.marginCall[i]]));update();
  } else {const sub=m.submodules.cross_hedge;r.innerHTML=section(sub,controlGrid(field('Correlation ρ','ch-rho',s.rho,{step:.01,min:-1,max:1})+field('σ_S','ch-sS',s.sS,{step:.001})+field('σ_F','ch-sF',s.sF,{step:.001})+field('Exposure Q_A','ch-QA',s.QA,{step:1000})+field('Contract size Q_F','ch-QF',s.QF,{step:1000})+selectField('Exposure','ch-exp',['will_purchase','own_or_will_sell'],s.exp)),`<div id="ch-metrics" class="metric-grid"></div>${chartBox('ch-chart','Lecture jet-fuel / heating-oil observations')}<div id="ch-reg"></div>`);
    const update=()=>{s.rho=getn('ch-rho');s.sS=getn('ch-sS');s.sF=getn('ch-sF');s.QA=getn('ch-QA');s.QF=getn('ch-QF');s.exp=getv('ch-exp');const x=F.crossHedge(s.rho,s.sS,s.sF,s.QA,s.QF,s.exp),reg=F.estimateCrossHedgeFromChanges(F.LECTURE_CROSS_HEDGE_DS,F.LECTURE_CROSS_HEDGE_DF);qs('#ch-metrics',r).innerHTML=metric('h*',num(x.hedgeRatio,4))+metric('R²',num(x.hedgeEffectiveness,4))+metric('N*',num(x.optimalContracts,2))+metric('Rounded contracts',x.roundedContracts)+metric('Direction',x.recommendedFuturesPosition);lineChart(qs('#ch-chart',r),[{name:'ΔS observations',x:F.LECTURE_CROSS_HEDGE_DF,y:F.LECTURE_CROSS_HEDGE_DS},{name:'Regression',x:[Math.min(...F.LECTURE_CROSS_HEDGE_DF),Math.max(...F.LECTURE_CROSS_HEDGE_DF)],y:[Math.min(...F.LECTURE_CROSS_HEDGE_DF),Math.max(...F.LECTURE_CROSS_HEDGE_DF)].map(z=>reg.intercept+reg.h*z)}],{xLabel:'ΔF',yLabel:'ΔS'});qs('#ch-reg',r).innerHTML=interpretation(`Lecture regression: ΔS ≈ ${reg.intercept.toFixed(4)} + ${reg.h.toFixed(4)} ΔF; ρ=${reg.rho.toFixed(4)}, R²=${reg.R2.toFixed(4)}.`)};bindNums(r,['ch-rho','ch-sS','ch-sF','ch-QA','ch-QF'],update);r.querySelector('#ch-exp').onchange=update;update();}
});}

// 3. Strategies
function renderStrategies(root){const m=CONTENT.modules.strategies,s=st('strategies',{preset:'Straddle',kl:90,ka:100,kh:110,ratio:2,netCost:8,r:.03,T:1,legs:[{instrument:'call',quantity:1,strike:100},{instrument:'put',quantity:1,strike:100},{instrument:'underlying',quantity:0,strike:100}]});tabbed('strategies',root,[['presets','Lecture strategies'],['custom','Custom portfolio'],['profit','Payoff vs profit']],(t,r)=>{
  const x=linspace(50,150,201);
  if(t==='presets'){const sub=m.submodules.presets;r.innerHTML=section(sub,controlGrid(selectField('Preset','st-preset',['Bull Spread','Collar','Collared Stock','Straddle','Strangle','Butterfly Spread','Ratio Spread'],s.preset)+field('K_low','st-kl',s.kl)+field('K_ATM','st-ka',s.ka)+field('K_high','st-kh',s.kh)+field('Ratio n','st-ratio',s.ratio,{step:1,min:1})),`<div id="st-legs"></div>${chartBox('st-chart','Expiration payoff')}`);const update=()=>{s.preset=getv('st-preset');s.kl=getn('st-kl');s.ka=getn('st-ka');s.kh=getn('st-kh');s.ratio=getn('st-ratio');try{const legs=F.strategyPreset(s.preset,s.kl,s.ka,s.kh,s.ratio);qs('#st-legs',r).innerHTML=table(['Leg','Quantity','Strike'],legs.map(l=>[l.label,l.quantity,l.strike??'—']));lineChart(qs('#st-chart',r),[{name:s.preset,x,y:x.map(ST=>F.portfolioPayoff(ST,legs))}],{xLabel:'S_T',yLabel:'Payoff'});}catch(e){qs('#st-legs',r).innerHTML=errorBox(e.message)}};['st-preset','st-kl','st-ka','st-kh','st-ratio'].forEach(id=>r.querySelector(`#${id}`)?.addEventListener('input',update));update();}
  else if(t==='custom'){const sub=m.submodules.custom;const legRows=s.legs.map((l,i)=>`<div class="leg-row">${selectField(`Leg ${i+1}` ,`leg-i-${i}`,['call','put','underlying'],l.instrument)}${field('Quantity',`leg-q-${i}`,l.quantity,{step:.5})}${field('Strike',`leg-k-${i}`,l.strike,{step:1})}</div>`).join('');r.innerHTML=`${theoryCard(sub)}<div class="lab-layout"><section class="panel"><div class="panel-title">Portfolio legs</div>${legRows}</section><section class="workspace">${chartBox('custom-chart','Custom expiration payoff')}<div id="custom-table"></div></section></div>`;const update=()=>{s.legs=s.legs.map((l,i)=>({instrument:getv(`leg-i-${i}`),quantity:getn(`leg-q-${i}`),strike:getn(`leg-k-${i}`)}));lineChart(qs('#custom-chart',r),[{name:'Portfolio',x,y:x.map(ST=>F.portfolioPayoff(ST,s.legs))}],{xLabel:'S_T',yLabel:'Payoff'});qs('#custom-table',r).innerHTML=table(['Instrument','Quantity','Strike'],s.legs.map(l=>[l.instrument,l.quantity,l.instrument==='underlying'?'—':l.strike]));};s.legs.forEach((_,i)=>['i','q','k'].forEach(z=>r.querySelector(`#leg-${z}-${i}`)?.addEventListener('input',update)));update();}
  else {const sub=m.submodules.profit;r.innerHTML=section(sub,controlGrid(selectField('Preset','pf-preset',['Bull Spread','Collar','Collared Stock','Straddle','Strangle','Butterfly Spread','Ratio Spread'],s.preset)+field('Net initial cost C₀','pf-cost',s.netCost,{step:.5})+field('Risk-free rate r','pf-r',s.r,{step:.005})+field('Maturity T','pf-T',s.T,{step:.25})),`${chartBox('profit-chart','Payoff versus profit at T')}<div id="profit-note"></div>`);const update=()=>{s.preset=getv('pf-preset');s.netCost=getn('pf-cost');s.r=getn('pf-r');s.T=getn('pf-T');const legs=F.strategyPreset(s.preset,s.kl,s.ka,s.kh,s.ratio),pay=x.map(ST=>F.portfolioPayoff(ST,legs)),profit=pay.map(v=>F.terminalProfitFromNetCost(v,s.netCost,s.r,s.T));lineChart(qs('#profit-chart',r),[{name:'Payoff',x,y:pay},{name:'Profit',x,y:profit}],{xLabel:'S_T',yLabel:'Value at T'});qs('#profit-note',r).innerHTML=interpretation(`The time-0 net cost grows to ${money(s.netCost*Math.exp(s.r*s.T),2)} at T and shifts the entire payoff curve by that amount.`)};['pf-preset','pf-cost','pf-r','pf-T'].forEach(id=>r.querySelector(`#${id}`)?.addEventListener('input',update));update();}
});}

// 4. Binomial
function renderBinomial(root){const m=CONTENT.modules.binomial,s=st('binomial',{S:41,K:40,r:.08,sigma:.30,T:1,n:2,delta:0,type:'call',style:'european',maxn:40});tabbed('binomial',root,[['tree','Tree & replication'],['convergence','Convergence']],(t,r)=>{
  if(t==='tree'){const sub=m.submodules.tree;r.innerHTML=section(sub,controlGrid(field('S₀','bi-S',s.S)+field('K','bi-K',s.K)+field('r','bi-r',s.r,{step:.005})+field('σ','bi-sig',s.sigma,{step:.01})+field('T','bi-T',s.T,{step:.25})+field('n periods','bi-n',s.n,{step:1,min:1,max:25})+field('δ','bi-d',s.delta,{step:.005})+selectField('Option','bi-type',['call','put'],s.type)+selectField('Exercise','bi-style',['european','american'],s.style)),`<div id="bi-metrics" class="metric-grid"></div>${chartBox('bi-tree','Recombining tree (first 5 steps)')}<div id="bi-node"></div>`);const update=()=>{['S','K','r','sig','T','n','d'].forEach(()=>{});s.S=getn('bi-S');s.K=getn('bi-K');s.r=getn('bi-r');s.sigma=getn('bi-sig');s.T=getn('bi-T');s.n=Math.max(1,Math.round(getn('bi-n')));s.delta=getn('bi-d');s.type=getv('bi-type');s.style=getv('bi-style');try{const b=F.priceBinomial(s.S,s.K,s.r,s.sigma,s.T,s.n,s.delta,s.type,s.style);qs('#bi-metrics',r).innerHTML=metric('Option price',money(b.price,6))+metric('u',num(b.u,6))+metric('d',num(b.d,6))+metric('p*',num(b.p,6))+metric('Root Δ',Number.isFinite(b.deltaTree[0][0])?num(b.deltaTree[0][0],6):'exercise')+metric('Root B',Number.isFinite(b.bondTree[0][0])?money(b.bondTree[0][0],6):'exercise');binomialTreeChart(qs('#bi-tree',r),b,5);const rows=[];for(let i=0;i<Math.min(s.n,4);i++)for(let j=0;j<=i;j++)rows.push([i,j,money(b.stockTree[i][j],3),money(b.optionTree[i][j],4),Number.isFinite(b.continuationTree[i][j])?money(b.continuationTree[i][j],4):'—',money(b.intrinsicTree[i][j],4),b.exerciseTree[i][j]?'Exercise':'Continue']);qs('#bi-node',r).innerHTML=table(['i','j','S','V','Continuation','Intrinsic','Decision'],rows);}catch(e){qs('#bi-metrics',r).innerHTML=errorBox(e.message)}};['bi-S','bi-K','bi-r','bi-sig','bi-T','bi-n','bi-d','bi-type','bi-style'].forEach(id=>r.querySelector(`#${id}`)?.addEventListener('input',update));update();}
  else {const sub=m.submodules.convergence;r.innerHTML=section(sub,controlGrid(field('S₀','bc-S',s.S)+field('K','bc-K',s.K)+field('r','bc-r',s.r,{step:.005})+field('σ','bc-sig',s.sigma,{step:.01})+field('T','bc-T',s.T,{step:.25})+field('δ','bc-d',s.delta,{step:.005})+field('Maximum n','bc-max',s.maxn,{step:1,min:2,max:200})),`${chartBox('bc-chart','Binomial convergence')}<div id="bc-note"></div>`);const update=()=>{s.S=getn('bc-S');s.K=getn('bc-K');s.r=getn('bc-r');s.sigma=getn('bc-sig');s.T=getn('bc-T');s.delta=getn('bc-d');s.maxn=Math.round(getn('bc-max'));const ns=Array.from({length:s.maxn},(_,i)=>i+1),vals=ns.map(n=>F.priceBinomial(s.S,s.K,s.r,s.sigma,s.T,n,s.delta,'call','european').price),bs=F.blackScholesPrice(s.S,s.K,s.r,s.sigma,s.T,s.delta,'call');lineChart(qs('#bc-chart',r),[{name:'Binomial',x:ns,y:vals},{name:'Black-Scholes',x:ns,y:ns.map(()=>bs)}],{xLabel:'Number of periods n',yLabel:'Call price'});qs('#bc-note',r).innerHTML=interpretation('The lecture emphasizes oscillating rather than necessarily monotone convergence toward the Black-Scholes value.');};bindNums(r,['bc-S','bc-K','bc-r','bc-sig','bc-T','bc-d','bc-max'],update);update();}
});}

// 5. Black-Scholes
function renderBlackScholes(root){const m=CONTENT.modules.black_scholes,s=st('black_scholes',{S:41,K:40,r:.08,sigma:.30,T:1,delta:0,type:'call',mu:.10,nPaths:1500,nSteps:80,seed:12345});tabbed('black_scholes',root,[['greeks','Price & Greeks'],['gbm','GBM paths'],['mc','Monte Carlo']],(t,r)=>{
  if(t==='greeks'){const sub=m.submodules.greeks;r.innerHTML=section(sub,controlGrid(field('S','bs-S',s.S)+field('K','bs-K',s.K)+field('r','bs-r',s.r,{step:.005})+field('σ','bs-sig',s.sigma,{step:.01})+field('T','bs-T',s.T,{step:.25})+field('δ','bs-d',s.delta,{step:.005})+selectField('Option','bs-type',['call','put'],s.type)),`<div id="bs-metrics" class="metric-grid"></div>${chartBox('bs-chart','Option value before expiration versus payoff at T')}`);const update=()=>{s.S=getn('bs-S');s.K=getn('bs-K');s.r=getn('bs-r');s.sigma=getn('bs-sig');s.T=getn('bs-T');s.delta=getn('bs-d');s.type=getv('bs-type');const g=F.blackScholesGreeks(s.S,s.K,s.r,s.sigma,s.T,s.delta,s.type);qs('#bs-metrics',r).innerHTML=metric('Price',money(g.price,6))+metric('Delta',num(g.delta,5))+metric('Gamma',num(g.gamma,5))+metric('Elasticity',num(g.elasticity,5))+metric('Vega / 1pp',num(g.vegaPer1Pct,5))+metric('Theta / day',num(g.thetaPerDay,5))+metric('Rho / 1pp',num(g.rhoPer1Pct,5))+metric('Psi / 1pp',num(g.psiPer1Pct,5));const x=linspace(Math.max(1,s.K*.5),s.K*1.5,160),v=x.map(S=>F.blackScholesPrice(S,s.K,s.r,s.sigma,s.T,s.delta,s.type)),p=x.map(S=>s.type==='call'?F.callPayoff(S,s.K):F.putPayoff(S,s.K));lineChart(qs('#bs-chart',r),[{name:'Black-Scholes value',x,y:v},{name:'Payoff at T',x,y:p}],{xLabel:'Stock price',yLabel:'Option value'});};['bs-S','bs-K','bs-r','bs-sig','bs-T','bs-d','bs-type'].forEach(id=>r.querySelector(`#${id}`)?.addEventListener('input',update));update();}
  else if(t==='gbm'){const sub=m.submodules.gbm;r.innerHTML=section(sub,controlGrid(field('S₀','gb-S',s.S)+field('μ (physical drift)','gb-mu',s.mu,{step:.01})+field('r','gb-r',s.r,{step:.005})+field('δ','gb-d',s.delta,{step:.005})+field('σ','gb-sig',s.sigma,{step:.01})+field('T','gb-T',s.T,{step:.25})+field('Paths','gb-np',s.nPaths,{step:100,min:100,max:5000})+field('Steps','gb-ns',s.nSteps,{step:10,min:10,max:252})+field('Seed','gb-seed',s.seed,{step:1})+selectField('Measure','gb-measure',['P','Q'],'P')+`<button id="gb-run" class="primary full">Run simulation</button>`),`<div id="gb-metrics" class="metric-grid"></div>${chartBox('gb-chart','Sample stock paths')} ${chartBox('gb-hist','Terminal stock-price distribution')}`);qs('#gb-run',r).onclick=async()=>{const b=qs('#gb-run',r);loading(b,true);try{s.S=getn('gb-S');s.mu=getn('gb-mu');s.r=getn('gb-r');s.delta=getn('gb-d');s.sigma=getn('gb-sig');s.T=getn('gb-T');s.nPaths=Math.round(getn('gb-np'));s.nSteps=Math.round(getn('gb-ns'));s.seed=Math.round(getn('gb-seed'));const measure=getv('gb-measure'),drift=measure==='P'?s.mu:s.r-s.delta,res=await runWorker('gbm',[s.S,drift,s.sigma,s.T,s.nPaths,s.nSteps,s.seed]),terms=res.paths.map(x=>x.at(-1));qs('#gb-metrics',r).innerHTML=metric('Measure',measure)+metric('Drift used',num(drift,4))+metric('Mean S_T',money(mean(terms),3))+metric('Paths simulated',s.nPaths.toLocaleString());const sample=res.paths.slice(0,Math.min(20,res.paths.length)).map((p,i)=>({name:i===0?'Path 1':'',x:res.times,y:p}));lineChart(qs('#gb-chart',r),sample,{xLabel:'Time',yLabel:'S_t'});histogram(qs('#gb-hist',r),terms,35,{xLabel:'S_T'});}catch(e){qs('#gb-metrics',r).innerHTML=errorBox(e.message)}finally{loading(b,false)}};}
  else {const sub=m.submodules.mc;r.innerHTML=section(sub,controlGrid(field('S₀','mc-S',s.S)+field('K','mc-K',s.K)+field('r','mc-r',s.r,{step:.005})+field('δ','mc-d',s.delta,{step:.005})+field('σ','mc-sig',s.sigma,{step:.01})+field('T','mc-T',s.T,{step:.25})+field('Paths','mc-n',Math.max(1000,s.nPaths),{step:1000,min:1000,max:100000})+field('Seed','mc-seed',s.seed,{step:1})+selectField('Option','mc-type',['call','put'],s.type)+`<button id="mc-run" class="primary full">Price by Monte Carlo</button>`),`<div id="mc-metrics" class="metric-grid"></div><div id="mc-note"></div>`);qs('#mc-run',r).onclick=async()=>{const b=qs('#mc-run',r);loading(b,true);try{const args=[getn('mc-S'),getn('mc-K'),getn('mc-r'),getn('mc-sig'),getn('mc-T'),getn('mc-d'),getv('mc-type'),Math.round(getn('mc-n')),Math.round(getn('mc-seed'))],x=await runWorker('mc',args);qs('#mc-metrics',r).innerHTML=metric('Monte Carlo estimate',money(x.estimate,6))+metric('Std. error',money(x.standardError,6))+metric('95% CI',`${money(x.ci95Low,4)} – ${money(x.ci95High,4)}`)+metric('Black-Scholes',money(x.exactBlackScholes,6));qs('#mc-note',r).innerHTML=interpretation(`Sampling error is ${money(x.standardError,6)}. Increasing paths changes numerical precision, not the pricing model.`);}catch(e){qs('#mc-metrics',r).innerHTML=errorBox(e.message)}finally{loading(b,false)}};}
});}

// 6. Hedging
function renderHedging(root){const m=CONTENT.modules.hedging,s=st('hedging',{K:110,T:.5,S0:100,r:.03,mu:.05,sigma:.2,nPaths:2500,nSteps:100,TC:0,K2:115,T2:1,seed:12345,gamma:false});tabbed('hedging',root,[['distribution','P&L distribution'],['path','One path'],['frequency','Rebalancing frequency']],(t,r)=>{
  const controls=controlGrid(field('Sold call K','hd-K',s.K)+field('T','hd-T',s.T,{step:.1})+field('S₀','hd-S',s.S0)+field('r','hd-r',s.r,{step:.005})+field('μ','hd-mu',s.mu,{step:.005})+field('σ','hd-sig',s.sigma,{step:.01})+field('Transaction cost ε','hd-TC',s.TC,{step:.0005})+field('Hedge call K̃','hd-K2',s.K2)+field('Hedge call T̃','hd-T2',s.T2,{step:.1})+field('Seed','hd-seed',s.seed,{step:1}));
  function args(np,ns,gamma,tc=s.TC){const S0=getn('hd-S'),K=getn('hd-K'),T=getn('hd-T'),rr=getn('hd-r'),mu=getn('hd-mu'),sig=getn('hd-sig'),K2=getn('hd-K2'),T2=getn('hd-T2'),seed=Math.round(getn('hd-seed')),charge=F.blackScholesPrice(S0,K,rr,sig,T,0,'call');return [charge,K,T,S0,rr,mu,sig,np,ns,tc,gamma,K2,T2,seed];}
  if(t==='distribution'){const sub=m.submodules.distribution;r.innerHTML=`${theoryCard(sub)}<div class="lab-layout"><section class="panel"><div class="panel-title">Inputs</div>${controls}${controlGrid(field('Paths','hd-np',s.nPaths,{step:500,min:500,max:10000})+field('Rebalancing steps','hd-ns',s.nSteps,{step:10,min:5,max:500})+selectField('Hedge','hd-gh',['Delta only','Delta-Gamma'],s.gamma?'Delta-Gamma':'Delta only'))}<button id="hd-run" class="primary full">Run hedging experiment</button></section><section class="workspace"><div id="hd-metrics" class="metric-grid"></div>${chartBox('hd-hist','Final bank balance / P&L')}</section></div>`;qs('#hd-run',r).onclick=async()=>{const b=qs('#hd-run',r);loading(b,true);try{const np=Math.round(getn('hd-np')),ns=Math.round(getn('hd-ns')),gh=getv('hd-gh')==='Delta-Gamma',x=await runWorker('hedging',args(np,ns,gh,getn('hd-TC')));qs('#hd-metrics',r).innerHTML=metric('Mean P&L',money(x.mean,5))+metric('Std. dev.',money(x.std,5))+metric('5% percentile',money(x.percentile5,5))+metric('Paths',np.toLocaleString());histogram(qs('#hd-hist',r),x.finalBalance,40,{xLabel:'Final balance'});}catch(e){qs('#hd-metrics',r).innerHTML=errorBox(e.message)}finally{loading(b,false)}};}
  else if(t==='path'){const sub=m.submodules.path;r.innerHTML=`${theoryCard(sub)}<div class="lab-layout"><section class="panel"><div class="panel-title">Inputs</div>${controls}${controlGrid(field('Path steps','hp-ns',80,{step:10,min:10,max:250})+selectField('Hedge','hp-gh',['Delta only','Delta-Gamma'],'Delta only'))}<button id="hp-run" class="primary full">Simulate one path</button></section><section class="workspace">${chartBox('hp-chart','Illustrative underlying path')}<div id="hp-note"></div></section></div>`;qs('#hp-run',r).onclick=async()=>{const b=qs('#hp-run',r);loading(b,true);try{const ns=Math.round(getn('hp-ns')),gh=getv('hp-gh')==='Delta-Gamma',S0=getn('hd-S'),T=getn('hd-T'),mu=getn('hd-mu'),sig=getn('hd-sig'),seed=Math.round(getn('hd-seed')),sim=await runWorker('gbm',[S0,mu,sig,T,1,ns,seed]);lineChart(qs('#hp-chart',r),[{name:'S_t',x:sim.times,y:sim.paths[0]}],{xLabel:'Time',yLabel:'Stock price'});const x=await runWorker('hedging',args(1,ns,gh,getn('hd-TC')));qs('#hp-note',r).innerHTML=interpretation(`For the same seed and model inputs, the final hedging balance is ${money(x.finalBalance[0],5)}. The distribution tab shows why one path alone is not a risk assessment.`);}finally{loading(b,false)}};}
  else {const sub=m.submodules.frequency;r.innerHTML=`${theoryCard(sub)}<div class="lab-layout"><section class="panel"><div class="panel-title">Inputs</div>${controls}${field('Paths per frequency','hf-np',1500,{step:500,min:500,max:5000})}<button id="hf-run" class="primary full">Compare frequencies</button></section><section class="workspace">${chartBox('hf-chart','P&L standard deviation versus rebalancing frequency')}<div id="hf-note"></div></section></div>`;qs('#hf-run',r).onclick=async()=>{const b=qs('#hf-run',r);loading(b,true);try{const np=Math.round(getn('hf-np')),steps=[20,50,100,200],no=[],tc=[];for(const ns of steps){no.push((await runWorker('hedging',args(np,ns,false,0))).std);tc.push((await runWorker('hedging',args(np,ns,false,getn('hd-TC')||.001))).std);}lineChart(qs('#hf-chart',r),[{name:'No transaction costs',x:steps,y:no},{name:'With transaction costs',x:steps,y:tc}],{xLabel:'Number of rebalancing steps',yLabel:'P&L Std Dev'});qs('#hf-note',r).innerHTML=interpretation('Without costs, finer rebalancing reduces discretization risk. With proportional costs, the lecture highlights that the overall effect need not be monotone.');}finally{loading(b,false)}};}
});}

// 7. Implied volatility and VIX
function renderImplied(root){const m=CONTENT.modules.implied_vol,s=st('implied_vol',{S:100,K:90,r:.08,T:1,delta:.05,market:18.25,type:'call',sigma:.22});tabbed('implied_vol',root,[['iv','Implied volatility'],['surface','Volatility surface'],['vix','VIX / variance']],(t,r)=>{
  if(t==='iv'){const sub=m.submodules.iv;r.innerHTML=section(sub,controlGrid(field('S','iv-S',s.S)+field('K','iv-K',s.K)+field('r','iv-r',s.r,{step:.005})+field('δ','iv-d',s.delta,{step:.005})+field('T','iv-T',s.T,{step:.25})+field('Market option price','iv-p',s.market,{step:.1})+selectField('Option','iv-type',['call','put'],s.type)),`<div id="iv-metrics" class="metric-grid"></div>${chartBox('iv-chart','Black-Scholes price as a function of σ')}`);const update=()=>{try{s.S=getn('iv-S');s.K=getn('iv-K');s.r=getn('iv-r');s.delta=getn('iv-d');s.T=getn('iv-T');s.market=getn('iv-p');s.type=getv('iv-type');const x=F.impliedVolatility(s.market,s.S,s.K,s.r,s.T,s.delta,s.type);qs('#iv-metrics',r).innerHTML=metric('Implied volatility',pct(x.sigma,4))+metric('Repriced option',money(x.modelPrice,6))+metric('Lower bound',money(x.lowerBound,4))+metric('Upper bound',money(x.upperBound,4));const sig=linspace(.001,Math.max(.8,x.sigma*1.8),160),p=sig.map(z=>F.blackScholesPrice(s.S,s.K,s.r,z,s.T,s.delta,s.type));lineChart(qs('#iv-chart',r),[{name:'BS model price',x:sig.map(z=>100*z),y:p},{name:'Market price',x:[0,100*Math.max(.8,x.sigma*1.8)],y:[s.market,s.market]}],{xLabel:'σ (%)',yLabel:'Option price'});}catch(e){qs('#iv-metrics',r).innerHTML=errorBox(e.message)}};['iv-S','iv-K','iv-r','iv-d','iv-T','iv-p','iv-type'].forEach(id=>r.querySelector(`#${id}`)?.addEventListener('input',update));update();}
  else if(t==='surface'){const sub=m.submodules.surface;r.innerHTML=`${theoryCard(sub)}<div class="lab-layout"><section class="panel"><div class="panel-title">Benchmark inputs</div>${controlGrid(field('S','vs-S',100)+field('r','vs-r',.02,{step:.005})+field('δ','vs-d',0,{step:.005})+field('Constant BS σ','vs-sig',s.sigma,{step:.01}))}<label class="field"><span>Optional market price grid CSV</span><textarea id="vs-csv" rows="7" placeholder="Leave blank for the flat Black-Scholes benchmark.\nRows = maturities 0.25,0.5,1; columns = strikes 80,90,100,110,120"></textarea></label><div class="small-note">The default is deliberately a flat Black-Scholes benchmark; the app does not invent a market smile. Paste observed/supplied prices to invert a non-flat surface.</div><button id="vs-run" class="primary full">Build surface</button></section><section class="workspace"><div id="vs-metrics" class="metric-grid"></div>${chartBox('vs-heat','Implied-volatility surface (heatmap)')}</section></div>`;qs('#vs-run',r).onclick=()=>{try{const S=getn('vs-S'),rr=getn('vs-r'),dd=getn('vs-d'),sig=getn('vs-sig'),K=[80,90,100,110,120],T=[.25,.5,1],txt=qs('#vs-csv',r).value.trim();let prices;if(txt){const rows=txt.split(/\n+/).map(z=>z.split(/[;,\s]+/).filter(Boolean).map(Number));if(rows.length!==T.length||rows.some(z=>z.length!==K.length))throw new Error('Expected 3 rows × 5 columns.');prices=rows;}else prices=T.map(tt=>K.map(kk=>F.blackScholesPrice(S,kk,rr,sig,tt,dd,'call')));const iv=T.map((tt,i)=>K.map((kk,j)=>100*F.impliedVolatility(prices[i][j],S,kk,rr,tt,dd,'call').sigma));heatmap(qs('#vs-heat',r),T,K,iv,{rowLabel:'T',colLabel:'K'});const flat=iv.flat();qs('#vs-metrics',r).innerHTML=metric('Minimum IV',`${Math.min(...flat).toFixed(2)}%`)+metric('Maximum IV',`${Math.max(...flat).toFixed(2)}%`)+metric('Data source',txt?'Supplied price grid':'Black-Scholes benchmark');}catch(e){qs('#vs-metrics',r).innerHTML=errorBox(e.message)}};qs('#vs-run',r).click();}
  else {const sub=m.submodules.vix;r.innerHTML=section(sub,controlGrid(field('S₀','vx-S',100)+field('r','vx-r',.02,{step:.005})+field('T (years)','vx-T',30/365,{step:.005})+field('Benchmark σ','vx-sig',.20,{step:.01})),`<div id="vx-metrics" class="metric-grid"></div>${chartBox('vx-chart','OTM option-strip contribution')}<div id="vx-note"></div>`);const update=()=>{const S=getn('vx-S'),rr=getn('vx-r'),T=getn('vx-T'),sig=getn('vx-sig'),Fw=S*Math.exp(rr*T),K=linspace(40,200,161),puts=K.map(k=>F.blackScholesPrice(S,k,rr,sig,T,0,'put')),calls=K.map(k=>F.blackScholesPrice(S,k,rr,sig,T,0,'call'),),x=F.discreteVixVariance(K,puts,calls,Fw,rr,T);qs('#vx-metrics',r).innerHTML=metric('Forward F₀,T',money(Fw,4))+metric('K₀',money(x.K0,2))+metric('Replicated variance',num(x.variance,6))+metric('Volatility',pct(x.volatility,3))+metric('VIX-style level',num(x.vixLevel,3));lineChart(qs('#vx-chart',r),[{name:'ΔK·Q(K)/K²',x:K,y:x.contribution}],{xLabel:'Strike K',yLabel:'Contribution'});qs('#vx-note',r).innerHTML=interpretation(`With a broad dense Black-Scholes strip, the discrete option replication approximates the benchmark variance σ²=${(sig*sig).toFixed(6)}. This is a numerical teaching benchmark, not a live CBOE feed.`)};bindNums(r,['vx-S','vx-r','vx-T','vx-sig'],update);update();}
});}

// 8. Heston
function renderHeston(root){const m=CONTENT.modules.heston,s=st('heston',{S:100,K:100,r:.03,T:1,nu0:.04,k:2,theta:.04,sigma:.3,rho:-.7,seed:12345});tabbed('heston',root,[['dynamics','Dynamics'],['pricing','Pricing'],['simulation','Simulation']],(t,r)=>{
  const controls=controlGrid(field('S₀','he-S',s.S)+field('r','he-r',s.r,{step:.005})+field('ν₀','he-nu',s.nu0,{step:.005})+field('k','he-k',s.k,{step:.1})+field('θ','he-theta',s.theta,{step:.005})+field('σ (vol of variance)','he-sig',s.sigma,{step:.02})+field('ρ','he-rho',s.rho,{step:.1,min:-1,max:1})+field('T','he-T',s.T,{step:.25}));
  if(t==='dynamics'){const sub=m.submodules.dynamics;r.innerHTML=`${theoryCard(sub)}<div class="lab-layout"><section class="panel"><div class="panel-title">Parameters</div>${controls}</section><section class="workspace"><div id="he-dyn-metrics" class="metric-grid"></div><div id="he-dyn-note"></div></section></div>`;const update=()=>{const k=getn('he-k'),th=getn('he-theta'),sig=getn('he-sig'),fm=F.fellerMargin(k,th,sig);qs('#he-dyn-metrics',r).innerHTML=metric('Long-run variance θ',num(th,5))+metric('Long-run volatility √θ',pct(Math.sqrt(th),2))+metric('Feller margin 2kθ−σ²',num(fm,6))+metric('Condition',fm>0?'Satisfied':'Not satisfied');qs('#he-dyn-note',r).innerHTML=interpretation('The lecture calls ν_t the stochastic volatility process informally, but more precisely it is instantaneous variance. The app keeps ν in variance units.');};bindNums(r,['he-k','he-theta','he-sig'],update);update();}
  else if(t==='pricing'){const sub=m.submodules.pricing;r.innerHTML=`${theoryCard(sub)}<div class="lab-layout"><section class="panel"><div class="panel-title">Inputs</div>${controls}${field('Strike K','he-K',s.K)}<button id="he-price" class="primary full">Price call</button></section><section class="workspace"><div id="he-price-metrics" class="metric-grid"></div>${chartBox('he-smile','Model-implied volatility by strike')}<div class="small-note">The lecture pricing slides retain a λ inside b₁,b₂ without defining it in the preceding risk-neutral dynamics. The web lab, like the validated Python reference, sets this internal λ_v=0 and does not expose an invented course parameter.</div></section></div>`;qs('#he-price',r).onclick=()=>{const b=qs('#he-price',r);loading(b,true);setTimeout(()=>{try{s.S=getn('he-S');s.r=getn('he-r');s.nu0=getn('he-nu');s.k=getn('he-k');s.theta=getn('he-theta');s.sigma=getn('he-sig');s.rho=getn('he-rho');s.T=getn('he-T');s.K=getn('he-K');const p=F.hestonCallPrice(s.S,s.K,s.r,s.T,s.nu0,s.k,s.theta,s.sigma,s.rho);qs('#he-price-metrics',r).innerHTML=metric('Call price',money(p.callPrice,6))+metric('P₁',num(p.P1,6))+metric('P₂',num(p.P2,6))+metric('Feller margin',num(F.fellerMargin(s.k,s.theta,s.sigma),5));const K=linspace(70,130,13),iv=K.map(kk=>{const pp=F.hestonCallPrice(s.S,kk,s.r,s.T,s.nu0,s.k,s.theta,s.sigma,s.rho).callPrice;return 100*F.impliedVolatility(pp,s.S,kk,s.r,s.T,0,'call').sigma});lineChart(qs('#he-smile',r),[{name:'Heston implied volatility',x:K,y:iv}],{xLabel:'Strike K',yLabel:'Implied volatility (%)'});}catch(e){qs('#he-price-metrics',r).innerHTML=errorBox(e.message)}finally{loading(b,false)}},20)};}
  else {const sub=m.submodules.simulation;r.innerHTML=`${theoryCard(sub)}<div class="lab-layout"><section class="panel"><div class="panel-title">Inputs</div>${controls}${controlGrid(field('Paths','he-np',800,{step:100,min:100,max:3000})+field('Steps','he-ns',100,{step:10,min:20,max:252})+field('Seed','he-seed',s.seed,{step:1}))}<button id="he-sim" class="primary full">Simulate Heston</button></section><section class="workspace">${chartBox('he-paths','Stock paths')}${chartBox('he-var','Instantaneous variance paths')}<div id="he-sim-metrics" class="metric-grid"></div></section></div>`;qs('#he-sim',r).onclick=async()=>{const b=qs('#he-sim',r);loading(b,true);try{const args=[getn('he-S'),getn('he-r'),getn('he-T'),getn('he-nu'),getn('he-k'),getn('he-theta'),getn('he-sig'),getn('he-rho'),Math.round(getn('he-np')),Math.round(getn('he-ns')),Math.round(getn('he-seed'))],x=await runWorker('hestonSim',args),n=Math.min(15,x.stockPaths.length);lineChart(qs('#he-paths',r),x.stockPaths.slice(0,n).map((y,i)=>({name:i===0?'S_t':'',x:x.times,y})),{xLabel:'Time',yLabel:'S_t'});lineChart(qs('#he-var',r),x.variancePaths.slice(0,n).map((y,i)=>({name:i===0?'ν_t':'',x:x.times,y})),{xLabel:'Time',yLabel:'ν_t'});qs('#he-sim-metrics',r).innerHTML=metric('Mean terminal S',money(mean(x.stockPaths.map(p=>p.at(-1))),3))+metric('Mean terminal variance',num(mean(x.variancePaths.map(p=>p.at(-1))),5))+metric('Paths',x.stockPaths.length.toLocaleString());}catch(e){qs('#he-sim-metrics',r).innerHTML=errorBox(e.message)}finally{loading(b,false)}};}
});}

// 9. Merton jump diffusion
function renderMertonJump(root){const m=CONTENT.modules.merton_jump,s=st('merton_jump',{S:100,K:100,r:.03,T:.75,sigma:.18,lam:.8,m:-.08,delta:.22,seed:12345});tabbed('merton_jump',root,[['dynamics','Dynamics'],['pricing','Pricing'],['smile','Smile'],['simulation','Simulation']],(t,r)=>{
  const controls=controlGrid(field('S₀','mj-S',s.S)+field('r','mj-r',s.r,{step:.005})+field('T','mj-T',s.T,{step:.25})+field('Diffusion σ','mj-sig',s.sigma,{step:.01})+field('Jump intensity λ','mj-lam',s.lam,{step:.1})+field('Mean log jump m','mj-m',s.m,{step:.02})+field('Log-jump std δ','mj-d',s.delta,{step:.02}));
  if(t==='dynamics'){const sub=m.submodules.dynamics;r.innerHTML=`${theoryCard(sub)}<div class="lab-layout"><section class="panel">${controls}</section><section class="workspace"><div id="mj-dyn" class="metric-grid"></div><div id="mj-dyn-note"></div></section></div>`;const update=()=>{const lam=getn('mj-lam'),mm=getn('mj-m'),dd=getn('mj-d'),T=getn('mj-T'),k=F.jumpCompensator(mm,dd);qs('#mj-dyn',r).innerHTML=metric('Jump compensator k',num(k,6))+metric('Expected jump count λT',num(lam*T,4))+metric('E[Y]',num(1+k,6))+metric('Risk-neutral drift adjustment −λk',num(-lam*k,6));qs('#mj-dyn-note',r).innerHTML=interpretation('The compensator keeps the risk-neutral expected return consistent after jumps are introduced. λ governs frequency, while m and δ govern the log jump-size distribution.');};bindNums(r,['mj-lam','mj-m','mj-d','mj-T'],update);update();}
  else if(t==='pricing'){const sub=m.submodules.pricing;r.innerHTML=`${theoryCard(sub)}<div class="lab-layout"><section class="panel">${controls}${field('Strike K','mj-K',s.K)}<button id="mj-price" class="primary full">Price call</button></section><section class="workspace"><div id="mj-price-metrics" class="metric-grid"></div><div id="mj-terms"></div></section></div>`;qs('#mj-price',r).onclick=()=>{try{s.S=getn('mj-S');s.r=getn('mj-r');s.T=getn('mj-T');s.sigma=getn('mj-sig');s.lam=getn('mj-lam');s.m=getn('mj-m');s.delta=getn('mj-d');s.K=getn('mj-K');const a=F.mertonCallPrice(s.S,s.K,s.r,s.T,s.sigma,s.lam,s.m,s.delta,'eq35'),b=F.mertonCallPrice(s.S,s.K,s.r,s.T,s.sigma,s.lam,s.m,s.delta,'eq36'),bs=F.blackScholesPrice(s.S,s.K,s.r,s.sigma,s.T,0,'call');qs('#mj-price-metrics',r).innerHTML=metric('Merton call',money(a.callPrice,6))+metric('Equivalent eq.36',money(b.callPrice,6))+metric('Black-Scholes diffusion only',money(bs,6))+metric('k',num(a.jumpCompensatorK,6));qs('#mj-terms',r).innerHTML=table(['j','Poisson weight','σ_j','Conditional BS','Contribution'],a.terms.slice(0,12).map(z=>[z.j,num(z.weight,6),num(z.conditionalSigma,5),money(z.conditionalBsPrice,5),money(z.contribution,5)]));}catch(e){qs('#mj-price-metrics',r).innerHTML=errorBox(e.message)}};qs('#mj-price',r).click();}
  else if(t==='smile'){const sub=m.submodules.smile;r.innerHTML=`${theoryCard(sub)}<div class="lab-layout"><section class="panel">${controls}<button id="mj-smile-run" class="primary full">Compute smile</button></section><section class="workspace">${chartBox('mj-smile','Merton-implied volatility')}<div id="mj-smile-note"></div></section></div>`;qs('#mj-smile-run',r).onclick=()=>{const S=getn('mj-S'),rr=getn('mj-r'),T=getn('mj-T'),sig=getn('mj-sig'),lam=getn('mj-lam'),mm=getn('mj-m'),dd=getn('mj-d'),K=linspace(70,130,25),iv=K.map(k=>{const p=F.mertonCallPrice(S,k,rr,T,sig,lam,mm,dd,'eq35').callPrice;return 100*F.impliedVolatility(p,S,k,rr,T,0,'call').sigma});lineChart(qs('#mj-smile',r),[{name:'Merton implied volatility',x:K,y:iv}],{xLabel:'Strike K',yLabel:'Implied volatility (%)'});qs('#mj-smile-note',r).innerHTML=interpretation('The smile is obtained by pricing under Merton and then inverting the Black-Scholes formula strike by strike.');};qs('#mj-smile-run',r).click();}
  else {const sub=m.submodules.simulation;r.innerHTML=`${theoryCard(sub)}<div class="lab-layout"><section class="panel">${controls}${controlGrid(field('Paths','mj-np',1000,{step:100,min:100,max:5000})+field('Steps','mj-ns',120,{step:10,min:20,max:252})+field('Seed','mj-seed',s.seed,{step:1}))}<button id="mj-sim" class="primary full">Simulate jump diffusion</button></section><section class="workspace">${chartBox('mj-paths','Stock paths')}${chartBox('mj-ret','Terminal log-return distribution')}<div id="mj-sim-metrics" class="metric-grid"></div></section></div>`;qs('#mj-sim',r).onclick=async()=>{const b=qs('#mj-sim',r);loading(b,true);try{const args=[getn('mj-S'),getn('mj-r'),getn('mj-T'),getn('mj-sig'),getn('mj-lam'),getn('mj-m'),getn('mj-d'),Math.round(getn('mj-np')),Math.round(getn('mj-ns')),Math.round(getn('mj-seed'))],x=await runWorker('mertonSim',args),n=Math.min(15,x.stockPaths.length),S0=args[0],rets=x.stockPaths.map(p=>Math.log(p.at(-1)/S0)),jumps=x.jumpCounts.map(p=>p.at(-1));lineChart(qs('#mj-paths',r),x.stockPaths.slice(0,n).map((y,i)=>({name:i===0?'S_t':'',x:x.times,y})),{xLabel:'Time',yLabel:'S_t'});histogram(qs('#mj-ret',r),rets,40,{xLabel:'log(S_T/S_0)'});qs('#mj-sim-metrics',r).innerHTML=metric('Mean realized jumps',num(mean(jumps),4))+metric('Theoretical λT',num(args[4]*args[2],4))+metric('Paths',x.stockPaths.length.toLocaleString());}finally{loading(b,false)}};}
});}

// 10. Merton structural credit
function renderMertonCredit(root){const m=CONTENT.modules.merton_credit,s=st('merton_credit',{V:12.4,D:10,r:.05,sigmaV:.2123,T:1,alpha:.08,E:3,sigmaE:.8});tabbed('merton_credit',root,[['capital','Capital structure'],['known','Known firm value'],['kmv','KMV-style inversion']],(t,r)=>{
  if(t==='capital'){const sub=m.submodules.capital;r.innerHTML=section(sub,controlGrid(field('Debt face value D','cr-D',s.D)+field('Max V(T) in chart','cr-max',25)),`${chartBox('cr-cap','Equity and debt payoffs at maturity')}<div id="cr-cap-note"></div>`);const update=()=>{s.D=getn('cr-D');const mx=getn('cr-max'),x=linspace(0,mx,180),eq=x.map(v=>Math.max(v-s.D,0)),debt=x.map(v=>Math.min(v,s.D));lineChart(qs('#cr-cap',r),[{name:'Equity E(T)',x,y:eq},{name:'Debt D(T)',x,y:debt}],{xLabel:'Firm value V(T)',yLabel:'Payoff'});qs('#cr-cap-note',r).innerHTML=interpretation(`Default occurs at maturity when V(T) < D = ${money(s.D,2)}. Equity is the payoff of a long call on firm value.`)};bindNums(r,['cr-D','cr-max'],update);update();}
  else if(t==='known'){const sub=m.submodules.known;r.innerHTML=section(sub,controlGrid(field('Firm value V₀','ck-V',s.V)+field('Debt face D','ck-D',s.D)+field('r','ck-r',s.r,{step:.005})+field('σ_V','ck-sv',s.sigmaV,{step:.01})+field('T','ck-T',s.T,{step:.25})+field('Physical drift α','ck-a',s.alpha,{step:.01})),`<div id="ck-metrics" class="metric-grid"></div><div id="ck-note"></div>`);const update=()=>{s.V=getn('ck-V');s.D=getn('ck-D');s.r=getn('ck-r');s.sigmaV=getn('ck-sv');s.T=getn('ck-T');s.alpha=getn('ck-a');const z=F.evaluateKnownFirm(s.V,s.D,s.r,s.sigmaV,s.T),dd=F.distanceToDefault(s.V,s.D,s.alpha,s.sigmaV,s.T),edf=F.expectedDefaultFrequency(s.V,s.D,s.alpha,s.sigmaV,s.T);qs('#ck-metrics',r).innerHTML=metric('Equity E₀',money(z.equityValue,5))+metric('Risky debt D₀',money(z.debtValue,5))+metric('Risk-neutral PD',pct(z.riskNeutralDefaultProbability,3))+metric('Physical distance to default',num(dd,4))+metric('Physical EDF',pct(edf,3))+metric('Credit spread',pct(z.creditSpread,3));qs('#ck-note',r).innerHTML=interpretation('The physical EDF uses α, while the risk-neutral default probability uses r. They are different objects and are reported separately.');};bindNums(r,['ck-V','ck-D','ck-r','ck-sv','ck-T','ck-a'],update);update();}
  else {const sub=m.submodules.kmv;r.innerHTML=section(sub,controlGrid(field('Observed equity E₀','km-E',s.E)+field('Observed equity volatility σ_E','km-se',s.sigmaE,{step:.05})+field('Debt face D','km-D',s.D)+field('r','km-r',s.r,{step:.005})+field('T','km-T',s.T,{step:.25})),`<div id="km-metrics" class="metric-grid"></div><div id="km-note"></div>`);const update=()=>{try{s.E=getn('km-E');s.sigmaE=getn('km-se');s.D=getn('km-D');s.r=getn('km-r');s.T=getn('km-T');const z=F.inferFirmValueFromEquity(s.E,s.sigmaE,s.D,s.r,s.T);qs('#km-metrics',r).innerHTML=metric('Inferred V₀',money(z.V0,5))+metric('Inferred σ_V',num(z.sigmaV,6))+metric('Risk-neutral PD',pct(z.riskNeutralDefaultProbability,3))+metric('Risky debt value',money(z.debtValue,5))+metric('Debt yield',pct(z.debtYieldContinuous,3))+metric('Credit spread',pct(z.creditSpread,3));qs('#km-note',r).innerHTML=interpretation('For the lecture benchmark E₀=3, σ_E=0.8, D=10, r=5%, T=1, the inversion returns V₀≈12.40 and σ_V≈0.2123.');}catch(e){qs('#km-metrics',r).innerHTML=errorBox(e.message)}};bindNums(r,['km-E','km-se','km-D','km-r','km-T'],update);update();}
});}

export function resetModuleState(id){ delete state[id]; delete activeTab[id]; }

export function renderModule(id,root){
  const map={forward:renderForward,futures:renderFutures,strategies:renderStrategies,binomial:renderBinomial,black_scholes:renderBlackScholes,hedging:renderHedging,implied_vol:renderImplied,heston:renderHeston,merton_jump:renderMertonJump,merton_credit:renderMertonCredit};
  (map[id]||(()=>{root.innerHTML=errorBox('Unknown module.')}))(root);
}
